# Generated by Django 4.2.11 on 2024-04-19 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('usr_uid', models.UUIDField(default=uuid.UUID('dfe134b8-b208-4c8e-a680-6fa88220caa8'), primary_key=True, serialize=False)),
            ],
        ),
    ]
