services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
  email_worker:
    build:
      celery_email_sander/
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq

  notification_watcher:
    build:
      celery_notification_watcher/
    volumes:
      - ./db:/app/db
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - SQLITE_URL=sqlite:///db/db.sqlite3
      - AUTO_CONFIRM=False
    depends_on:
      - rabbitmq
      - app
    restart:
      always

  notification_beat:
    build:
      celery_beatmaker/
    volumes:
      - ./celery_notification_watcher:/app/celery_notification_watcher
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
    restart:
      always


  app:
    build:
      ./
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./static:/static
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - AUTO_CONFIRM=False