services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
  email_worker:
    build:
      context: ./celery_email_sander
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq

  notification_watcher:
    build:
      context: ./celery_notification_watcher
    volumes:
      - db-data:/app/celery_notification_watcher/db
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
      - app

  notification_beat:
    build:
      context: ./celery_beatmaker
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq


  app:
    image: avia-sales-app:latest
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app/db
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//

volumes:
  db-data: