# Generated by Django 4.2.11 on 2024-04-19 06:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0002_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('from_country', models.CharField(max_length=30)),
                ('to_country', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
                ('flight_date', models.CharField(max_length=30)),
                ('back_date', models.CharField(max_length=30)),
                ('fly_time', models.CharField(max_length=30)),
                ('allowed', models.BooleanField(default=True, max_length=30)),
                ('ticket_uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
    ]
