# Generated by Django 4.2.11 on 2024-04-19 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time',
        ),
    ]
